menu:
    博客: /blog/
    归档: /blog/archives/
    twitter: http://twitter.com/kokdemo
    github: https://github.com/kokdemo
    rss: /blog/atom.xml

favicon: /favicon.ico
logo: /box.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: 

# Analytics
# google-analytics:
#ga: UA-65933410-1
# baidu-analytics:
#ba: //hm.baidu.com/hm.js?a36e15d9e2adec9a21fcdd9f686b1ed2

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
